// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfOOxu1KGl9-eGlx9A194JxkYuer8q-c',
    appId: '1:54737180655:android:317d712bb425d74093c81a',
    messagingSenderId: '54737180655',
    projectId: 'saken2',
    storageBucket: 'saken2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrdlhLiSPbUKKvAHZFUFXyztYcsASdkv0',
    appId: '1:54737180655:ios:45b43a23752e3f6a93c81a',
    messagingSenderId: '54737180655',
    projectId: 'saken2',
    storageBucket: 'saken2.firebasestorage.app',
    androidClientId: '54737180655-vgijrg0khfhhgs831a0afbsnub72349m.apps.googleusercontent.com',
    iosClientId: '54737180655-rle5hff7k12il3ejkfuo2eleviq0nksg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakenMobile',
  );

}